### ISSUE TITLE
feat: ✨ Add the ability to activate a configuration profile at startup

### ISSUE THREAD

**Issue by philippart-s** [slidesk/slidesk#108]
**Is your feature request related to a problem? Please describe.**
It's a feature not a problem.

**Describe the solution you'd like**
To avoid duplicating code when little changes, it would be a good idea to have a configuration flag at startup to enable the desired configuration.  
For instance : `slidesk --config myconf`

**Describe alternatives you've considered**
An alternative is to create branch with a new config file.

**Additional context**
N/A

**Comment by gouz** [comment]
Imagine you have the following structure:

- .env
- snowcamp.env
- tnt.env

Which solution do you prefer?

1. Naming
`slidesk --config snowcamp` will launch the presentation using `snowcamp.env`

2. File
`slidesk --config snowcamp.env` will launch the presentation using `snowcamp.env`

**Comment by philippart-s** [comment]
> Imagine you have the following structure:
> 
>     * .env
> 
>     * snowcamp.env
> 
>     * tnt.env
> 
> 
> Which solution do you prefer?
> 
>     1. Naming
>        `slidesk --config snowcamp` will launch the presentation using `snowcamp.env`
> 
>     2. File
>        `slidesk --config snowcamp.env` will launch the presentation using `snowcamp.env`

I prefer the first, even if it means respecting a single kind of file extension, but I find it simpler 😉

**Comment by gouz** [comment]
will be available in 2.4.0 ;)
