### ISSUE TITLE
? bug: 🐛 Automatic hot reload seams not working anymore on FF

### ISSUE THREAD

**Issue by philippart-s** [slidesk/slidesk#109]
**Is your feature request related to a problem? Please describe.**
With FF when I change a file I must stop the slidesk CLI and relaunch it to see the update.

**Describe the solution you'd like**
In my memory the CLI detected the change in a slide and reload it automatically.
It is a good feature but if it was not the case, forget it.

**Describe alternatives you've considered**
Relaunch the CLI

**Additional context**
N/A

**Comment by gouz** [comment]
Since [2.3.9](https://github.com/slidesk/slidesk/releases/tag/2.3.9) the watcher is not active per default, you have to use the -w option

**Comment by philippart-s** [comment]
oh, sorry I've missed this change 😉, 👍
