### ISSUE TITLE
feat: ✨ Do not delete all folder without asking with -s option

### ISSUE THREAD

**Issue by philippart-s** [slidesk/slidesk#110]
**Is your feature request related to a problem? Please describe.**
The `-s <path>` option delete all the target `<path>` without show a prompt to validate the action.
It could be a problem when you set `.` as path, it will delete all the project and as it will not prompt to confirm the deletion you can't abord the operation 😅.

**Describe the solution you'd like**
A simple prompt asking to confirm what will be deleted.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by gouz** [comment]
Will be fix in the next release

**Comment by gouz** [comment]
Thanks for the report and idea
