### ISSUE TITLE
bug: 🐛 Some bugs on the demo slides (https://slidesk.github.io/slidesk)

### ISSUE THREAD

**Issue by philippart-s** [slidesk/slidesk#117]
**Is your feature request related to a problem? Please describe.**
I think there are few issues on the demo slides (https://slidesk.github.io/slidesk).

 - The X in the left top corner does nothing (on FF)
 - The button on the right bottom does noting (on FF)
 - The FR version is in English
 - The EN version display a 404 when I choose it in the drop down list

**Describe the solution you'd like**

Fix the issues or document their usage.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by gouz** [comment]
- The X in the left top corner does nothing (on FF)
- The button on the right bottom does noting (on FF)

=> It's normal, cause I use something available only on FF126 : https://caniuse.com/?search=popover
