### ISSUE TITLE
handle Markdown syntax to manage all basic HTML elements

### ISSUE THREAD

**Issue by taorepoara** [slidesk/slidesk#125]
**Is your feature request related to a problem? Please describe.**
I tried to use some Markdown elements for a presentation like third level titles, links or code block, but those elements are not managed yet.

**Describe the solution you'd like**
It would be nice to base Slidesk syntax on default Markdown syntax and use an existing Markdown parser that can be extended to generate the HTML.
I found [Marked](https://marked.js.org/using_pro#renderer) that could be easily configured to do what is needed.

**Describe alternatives you've considered**
The alternative I imagine is to implement and maintain the most common markdown elements, but it can be complicated.

**Additional context**
![Capture d’écran du 2024-04-23 16-35-55](https://github.com/slidesk/slidesk/assets/8969556/2ad794bd-4c80-48a9-a9ba-40f8927a4d7b)
![Capture d’écran du 2024-04-23 16-35-29](https://github.com/slidesk/slidesk/assets/8969556/a3290ef1-5a63-44c1-a507-bd3631783e14)

**Comment by gouz** [comment]
Available in next version

**Comment by gouz** [comment]
@taorepoara can I close ?

**Comment by taorepoara** [comment]
Yes, it works fine !
