### ISSUE TITLE
Do not parse elements in code blocks

### ISSUE THREAD

**Issue by taorepoara** [slidesk/slidesk#134]
**Is your feature request related to a problem? Please describe.**
Some elements break code blocks like empty lines or `/*` that is interpreted as a note start.

The code blocks content shouldn't be parsed.

**Describe the solution you'd like**
I'd that every thing that is in a code block is ignored.

**Describe alternatives you've considered**

**Additional context**

here is an example of problematic code block:

```dockerfile
# syntax=docker/dockerfile:1.4
# builder-0
FROM maven:3.9-eclipse-temurin-17-alpine AS builder-0
WORKDIR /app
ADD --link . ./
USER 0
RUN \
    --mount=type=cache,sharing=locked,uid=0,gid=0,target=/root/.m2\
    --mount=type=cache,sharing=locked,uid=0,gid=0,target=/app/target\
    mvn package -DskipTests && \
    mv target/*.jar app.jar
# runtime
FROM eclipse-temurin:17-jre-alpine AS runtime
COPY --link --chown=1000:1000 --from=builder-0 "/app/app.jar" "app.jar"
USER 1000
CMD ["java","-jar","app.jar"]
```

**Comment by gouz** [comment]
https://github.com/slidesk/slidesk/releases/tag/2.6.5

**Comment by gouz** [comment]
fixed in https://github.com/slidesk/slidesk/releases/tag/2.6.6
