### ISSUE TITLE
bug: 🐛 Null id on first slide

### ISSUE THREAD

**Issue by philippart-s** [slidesk/slidesk#135]
**Is your feature request related to a problem? Please describe.**
After update to the 2.6.6 version the id of the first slide is `null` instead of empty.
`http://localhost:1337/#` --> `http://localhost:1337/#null`

**Describe the solution you'd like**
A good thinks will be to be back to the empty value.

**Describe alternatives you've considered**
N/A

**Additional context**
The presentation is usable.

**Comment by gouz** [comment]
will be fixed into the next version ;)
