### ISSUE TITLE
bug:  🐛 Markdown not interpreted inside HTML tags

### ISSUE THREAD

**Issue by philippart-s** [slidesk/slidesk#136]
**Is your feature request related to a problem? Please describe.**
When markdown is inserted between two HTML tags it's not interpreted.
`<h2>**hello**, _world_</h2>` render `**hello**, _world_`

**Describe the solution you'd like**
I think it should render **hello**, _world_

**Describe alternatives you've considered**
It is possible to not use markdown in HTML tags and use CSS to style the font.

**Additional context**
Version: 2.6.6

**Comment by taorepoara** [comment]
Actually it is interpreted, but you'll have to make it multiline: 

```md
<h2>

**hello**, _world_
</h2>
```

The blank line after the opening tag is required to work.

**Comment by gouz** [comment]
I replace marked by showdown, then you can have markdown in HTML with this following syntax

```
<h2 markdown>**hello**, _world_</h2>
```

will be replaced with

```html
<h2><strong>hello</strong>, <em>world</em></h2>
```
