### ISSUE TITLE
enhancement: ✨ Do not require a blank line after the end of each slides

### ISSUE THREAD

**Issue by philippart-s** [slidesk/slidesk#137]
**Is your feature request related to a problem? Please describe.**
If the slides are splitted in several files a blank line must be present between each slides.
For example if I have these slides:
```
## Slide 1
Wonderful first slide
```
```
## Slide 2
Wonderful second slide
```
And `main.sdf`:
```
## Welcome slide

!include(slides/slide-one.sdf)
!include(slides/slide-two.sdf)
```

This setting will break the navigation.
To fix it (add a blank line between each `include`):
```
## Welcome slide

!include(slides/slide-one.sdf)

!include(slides/slide-two.sdf)
```

or (add blank line at the end of each slide)
```
## Slide 1
Wonderful first slide

```
```
## Slide 2
Wonderful second slide

```
```
## Welcome slide

!include(slides/slide-one.sdf)
!include(slides/slide-two.sdf)
```

**Describe the solution you'd like**
Ideally the navigation should work event if there is no blank line.

**Describe alternatives you've considered**
See solutions above.

**Additional context**
Version: 2.6.6

**Comment by gouz** [comment]
will be fixed in next version
