### ISSUE TITLE
bug: (?) 🐛 Links on last slide are clikable on all slides

### ISSUE THREAD

**Issue by philippart-s** [slidesk/slidesk#143]
**Is your feature request related to a problem? Please describe.**
If you add links on last slide the links are clickable but not displayed on each slides 

**Describe the solution you'd like**
I'd like to not have these hidden links on each slides 😉 

**Describe alternatives you've considered**
Create an empty slide at the end

**Additional context**
SliDesk v 2.6.9

**Comment by gouz** [comment]
fix with : https://github.com/slidesk/slidesk-extras/commit/0c68cd129a1204b1863c03243a544b07ae9ff850

**Comment by philippart-s** [comment]
👍
