### ISSUE TITLE
bug: (?) 🐛 Developer console not on current slide when using inspector

### ISSUE THREAD

**Issue by philippart-s** [slidesk/slidesk#144]
**Is your feature request related to a problem? Please describe.**
When the browser web developer console is activated, even if a component (for instance the title) of the current slide is selected, the code of the last slide is displayed. 

**Describe the solution you'd like**
It will be more convenient if the displayed code was the one of the current slide.

**Describe alternatives you've considered**
Browse the code in the developer console to find the code of the current slide.

**Additional context**
SliDesk version 2.6.9, tested on FF and Chromium.
It works with previous version of SliDesk (2.6.6?)

**Comment by gouz** [comment]
fix with : https://github.com/slidesk/slidesk-extras/commit/0c68cd129a1204b1863c03243a544b07ae9ff850

**Comment by philippart-s** [comment]
👍
