### ISSUE TITLE
feat: ✨ CLI to install and update plugins

### ISSUE THREAD

**Issue by philippart-s** [slidesk/slidesk#145]
**Is your feature request related to a problem? Please describe.**
N/A

**Describe the solution you'd like**
It will be great if the SliDesk CLI allow the installation of a plugin (and its update).
For example to install the _animate_ plugin:`slidesk plugin install animate`.  
To update it: `slidesk plugin update animate`.  
To remove it: `slidesk plugin delete animate`.  
And perhaps a global update of all plugins: `slidesk plugin update-all`.  
At the launch of SliDesk, it can check if some plugins should be updated and say it in the logs.
Perhaps a way to disable the check to speed the SliDesk launch.

It's a proposal not a mandatory feature 😉 

**Describe alternatives you've considered**
Use the actual way: manage the plugins manually.

**Additional context**
N/A

**Comment by gouz** [comment]
Available in the new release ;) 2.7.0

`update-all` will be available in the future
