### ISSUE TITLE
Change favicon

### ISSUE THREAD

**Issue by yodamad** [slidesk/slidesk#149]
Even if slidesk icon is super cool, it could be nice to be able to change de favicon of the slides

**Comment by gouz** [comment]
Nice idea, must favicon be svg only or can be in any format ?

**Comment by yodamad** [comment]
the more the best probably ;) 
I think that default extension is `.ico` and not `.svg`

**Comment by gouz** [comment]
Release https://github.com/slidesk/slidesk/releases/tag/2.7.2 fix this issue

**Comment by yodamad** [comment]
Try it on `2.7.2`(with Docker 🐳), it seems not to work

I've just created a `favicon.ico` in the root directory like in the example, but favicon is not displayed.
Nothing appears in the logs FYI

**Comment by yodamad** [comment]
@gouz : cannot reopen the issue on my side
