### ISSUE TITLE
🐛  `bad CPU type in executable` on MacOS

### ISSUE THREAD

**Issue by yodamad** [slidesk/slidesk#152]
Since several versions, it's not possible to run the binary on MacOS (with a x86 CPU).

Error is 
```sh
❯ slidesk
zsh: bad CPU type in executable: slidesk
````

Alternative is to use Docker image, but not always convenient

**Comment by gouz** [comment]
Next version of SliDesk will be built on both architecture

**Comment by yodamad** [comment]
Fix in `2.7.4` 💪
