### ISSUE TITLE
💡 Add css class support for `!image`

### ISSUE THREAD

**Issue by yodamad** [slidesk/slidesk#153]
**Is your feature request related to a problem? Please describe.**
css can be quite verbose. Add css to customize an image can create very long line, not very readable.
Having an option in the image keyword could be interesting

**Describe the solution you'd like**
A new attribute in the `!image` to specify one (or several class) to apply to the image

**Comment by gouz** [comment]
Available in next version

**Comment by yodamad** [comment]
2.7.4 ?

**Comment by gouz** [comment]
Yes

**Comment by yodamad** [comment]
@gouz : works with 1 class as explained in doc 🤘

Would it be complex to be able to have a list of class ? 😇

**Comment by gouz** [comment]
Will be available in next version :

Since version 2.7.6, in the `additional styles` you can specify many classes with this following syntax: `!image(path/of/your/image, my alternative text, 13, 12, [class1 class2 class3])` and the image will have these classes.
