### ISSUE TITLE
🔨  Set tab title in `.env` 

### ISSUE THREAD

**Issue by yodamad** [slidesk/slidesk#156]
For now, Slidesk take the title of the first slide as the title displayed in the tab name.
Sometimes, it's too long, or contains some HTML or MD  characters making it "ugly"

It could be nice to be able to set the title in the `.env` file to override this behavior when necessary

**Comment by gouz** [comment]
Available in 2.7.6

https://github.com/slidesk/slidesk/pull/157/commits/4585ca9e6ce83d43b3ef8be1b0540d1b95ac3658
